# Generated by Django 4.2.4 on 2024-04-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_freetrialuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('total_formatted', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Subscription Payment',
                'verbose_name_plural': 'Subscription Payments',
            },
        ),
    ]
