# Generated by Django 4.2.4 on 2024-05-03 22:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rssdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.PositiveIntegerField(unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_formatted', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='subscription_id',
            field=models.PositiveIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
