# Generated by Django 4.2.4 on 2024-05-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cancelledsubscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledsubscription',
            name='event_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cancelledsubscription',
            name='status',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cancelledsubscription',
            name='user_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='event_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='status',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='total_formatted',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='user_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(max_length=500),
        ),
    ]
