# Generated by Django 4.2.4 on 2024-05-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_cancelledsubscription_event_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledsubscription',
            name='event_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cancelledsubscription',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cancelledsubscription',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='event_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='total_formatted',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(max_length=100),
        ),
    ]
