# Generated by Django 4.2.4 on 2024-06-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_rssdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssdetails',
            name='rss_url',
            field=models.URLField(max_length=500),
        ),
    ]
